alert('Fashionista, here I come!');
window.open("http://www.nelly.com");
window.open("http://hm.com");
window.open("http://zara.com");
window.open("http://michaelkors.com/");
// window.open("http://google.com/search?q=kenza");
// window.open("http://google.com/search?q=karl lagerfeldt");
// window.open("http://google.com/search?q=bottega veneta boots");
// window.open("http://google.com/search?q=milan fashion week 2020");
// window.open("http://google.com/search?q=spring summer 2020 fashion trends shoes");
// window.open("http://google.com/search?q=chanel väska");
window.open("http://google.com/search?q=louis vuitton");
window.open("http://google.com/search?q=pojkvän slips");
window.open("http://google.com/search?q=nike running ladies fashion");
window.open("https://www.sandro-paris.com/");
window.open("https://www.mulberry.com/");
window.open("https://www.united-athle.jp/lookbook/");
window.open("https://nk.se/");
window.open("https://lassepedersen.biz/");
window.open("https://humankindmgmt.com/");
window.open("https://elle.com/");
window.open("https://vogue.com/");
window.open("https://gucci.com/");
